# Generated by Django 4.2.6 on 2023-10-27 09:57

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                (
                    'login',
                    models.CharField(
                        max_length=30,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                8, 'Количество символов должно быть не менее 8'
                            )
                        ],
                        verbose_name='Логин',
                    ),
                ),
                (
                    'password',
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='Пароль должен состоять из 8 символов, строчной и заглавной буквы, цифры и специального символа',
                                regex='^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*\\W)[A-Za-z\\d\\W]{8,}$',
                            )
                        ],
                        verbose_name='Пароль',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                4, 'Количество символов должно быть не менее 4'
                            )
                        ],
                        verbose_name='Наименование компании',
                    ),
                ),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('town', models.CharField(max_length=50, verbose_name='Город')),
                (
                    'foundation_date',
                    models.DateField(verbose_name='Дата основания компании'),
                ),
                ('site_href', models.CharField(max_length=200, verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                (
                    'technology',
                    models.CharField(max_length=100, verbose_name='Технологии'),
                ),
            ],
            options={
                'verbose_name': 'Технология',
                'verbose_name_plural': 'Технологии',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                (
                    'name',
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                2, 'Количество символов должно быть не менее 2'
                            )
                        ],
                        verbose_name='Должность',
                    ),
                ),
                ('town', models.CharField(max_length=150, verbose_name='Город')),
                ('salary', models.PositiveIntegerField(verbose_name='Зарплата')),
                (
                    'description',
                    models.TextField(max_length=10000, verbose_name='Описание'),
                ),
                (
                    'published_datetime',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата и время публикации'
                    ),
                ),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='core.company'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                (
                    'login',
                    models.CharField(
                        max_length=30,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                8, 'Количество символов должно быть не менее 8'
                            )
                        ],
                        verbose_name='Логин',
                    ),
                ),
                (
                    'password',
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='Пароль должен состоять из 8 символов, строчной и заглавной буквы, цифры и специального символа',
                                regex='^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*\\W)[A-Za-z\\d\\W]{8,}$',
                            )
                        ],
                        verbose_name='Пароль',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                2, 'Количество символов должно быть не менее 2'
                            )
                        ],
                        verbose_name='Имя',
                    ),
                ),
                (
                    'surname',
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                2, 'Количество символов должно быть не менее 2'
                            )
                        ],
                        verbose_name='Фамилия',
                    ),
                ),
                (
                    'patronymic',
                    models.CharField(
                        blank=True,
                        max_length=100,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                2, 'Количество символов должно быть не менее 2'
                            )
                        ],
                        verbose_name='Отчество',
                    ),
                ),
                (
                    'born_date',
                    models.DateField(default=None, verbose_name='Дата рождения'),
                ),
                ('technologies', models.ManyToManyField(to='core.technology')),
            ],
            options={
                'verbose_name': 'Специалист',
                'verbose_name_plural': 'Специалисты',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                (
                    'position',
                    models.CharField(max_length=150, verbose_name='Должность'),
                ),
                ('salary', models.CharField(max_length=100, verbose_name='Зарплата')),
                (
                    'published_datetime',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='Дата и время публикации'
                    ),
                ),
                (
                    'specialist',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='core.specialist',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.CheckConstraint(
                check=models.Q(('foundation_date__lte', datetime.date(2023, 10, 27))),
                name='foundation_date_constraint',
            ),
        ),
        migrations.AddConstraint(
            model_name='specialist',
            constraint=models.CheckConstraint(
                check=models.Q(('born_date__lte', datetime.date(2023, 10, 27))),
                name='born_date_constraint',
            ),
        ),
    ]
