name: Linters
on: [ push, pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
        with:
          python-version: ${{ matrix.python-version }}
  black:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.11' ]
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          python-version: ${{ matrix.python-version }}
